MainProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from app_core.views import *
from app_core.admin_views import *


urlpatterns = [

    path("admin/", admin.site.urls),
    path("", welcome_page, name="welcome-page"),
    path("admin_home", admin_home, name="admin-welcome-page"),
    path("login", login_page, name="login-page"),
    path("login_user", login_user, name="login-user"),
    path("logout_user", logout_page, name="logout-user"),
    path("register", register_page, name="register-user"),
    path("contact", contact, name="contact"),
    path("faq", faqq, name="faq"),
    path("about", about, name="about"),
    path("app/", include("app_core.urls", namespace="app")),

]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app_core/urls.py
from django.contrib import admin
from django.urls import path
from .user_views import *
from app_core.admin_views import *


app_name = "app"

urlpatterns = [

    # Users Urls ====================

    path("suites", view_suites, name = "view-suites"),
    path("suite_details/<str:suite_id>", suite_details, name = "suite-details"),
    path("payment", payment, name = "payment"),
    path("suite_request", suite_request, name = "suite-request"),
    path("room_transfer", room_transfer, name = "room-transfer"),
    path("complain", complaints, name = "complaints"),
    path("room_service", room_service, name = "room_service"),
    path("request_dashboard", request_dashboard, name = "request-dashboard"),

    # Admin Urls =======================

    path("create_package", create_package, name = "create-package"),
    path("create_wing_manager", create_wing_manager, name = "create-wing-manager"),
    path("create_wing", create_wing, name = "create-wing"),
    path("create_suite", create_suite, name = "create-suite"),
    path("create_room_service", create_room_service, name = "create-room-service"),
    
    path("manage_request", manage_request, name = "manage-request"),
    path("manage_suite_change", manage_suite_change, name = "manage-suite-change"),
    path("manage_help_request", manage_help_request, name = "manage-help-request"),
    path("manage_rule", manage_rule, name = "manage-rule"),
    path("manage_room_service", manage_room_service, name = "manage-room-service"),
    path("approve_or_disapprove/<str:ac_id>", approve_or_disapprove, name = "approve_or_disapprove"),
    path("help_request_status/<str:complain_id>", help_request_status, name = "help-request-status"),
    path("suite_change_status/<str:transfer_id>", suite_change_status, name = "suite-change-status"),
    path("room_service_request_status/<str:rors_id>", room_service_request_status, name = "room-service-request-status"),

]

app_core/models.py
from django.db import models
from django.contrib.auth.models import User


class Wallet(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    account_bal = models.BigIntegerField(default=0)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.account_bal} - {self.user.username}"


class Package(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=20)
    charge = models.BigIntegerField()
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.name


class WingManager(models.Model):
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    email = models.CharField(max_length = 50)
    address = models.CharField(max_length = 50)
    phone_no = models.CharField(max_length = 100)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.first_name


class Wing(models.Model):
    wing_manager = models.ForeignKey(WingManager, on_delete = models.CASCADE)
    wing_name = models.CharField(max_length = 50)
    wing_number = models.BigIntegerField(null = True)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.wing_name


class Room(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    wing = models.ForeignKey(Wing, on_delete = models.CASCADE)
    package = models.ForeignKey(Package, on_delete = models.CASCADE)
    room_number = models.IntegerField(unique=True)
    room_tag = models.CharField(max_length = 10, default="NEW")
    condition = models.CharField(max_length=50)
    is_available = models.BooleanField(default=True)
    image1 = models.FileField(default="default.png")
    image2 = models.FileField(default="default.png")
    image3 = models.FileField(default="default.png")
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.package.name} - {self.room_number}"


class RoomService(models.Model):
    wing = models.ForeignKey(Wing, on_delete = models.CASCADE)
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    phone_number = models.CharField(max_length = 50)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.first_name


class SuiteRequest(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    nights = models.IntegerField(default=1)
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.user.username} - {self.room.room_number}"


class HelpRequest(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    subject = models.CharField(max_length = 40)
    message = models.TextField()
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.user.first_name} - {self.subject}"


class RoomServiceRequest(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    subject = models.CharField(max_length = 40)
    message = models.TextField()
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.user.username} - {self.room.room_number}"


class SuiteChange(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room_from = models.ForeignKey(Room, on_delete=models.CASCADE, null=True, related_name="room_from")
    room_to = models.ForeignKey(Room, on_delete=models.CASCADE, null=True, related_name="room_to")
    reason = models.TextField()
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"Transfer {self.user.first_name} From Suite {self.room_from.room_number} To Suite {self.room_to.room_number}"


class Deposit(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    full_name = models.CharField(max_length = 200)
    card_number = models.CharField(max_length=20)
    cvv = models.CharField(max_length = 6)
    expire = models.CharField(max_length = 6)
    amount = models.IntegerField()
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.user.username


class Guideline(models.Model):
    rule = models.TextField()
    guideline1 = models.CharField(max_length = 250)
    guideline2 = models.CharField(max_length = 250)
    guideline3 = models.CharField(max_length = 250)
    guideline4 = models.CharField(max_length = 250)
    guideline5 = models.CharField(max_length = 250)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.rule[:20]}"


class FAQ(models.Model):
    fullname = models.CharField(max_length=100)
    question = models.CharField(max_length=200)

    def __str__(self):
        return self.question

app_core/views.py
from django.shortcuts import *
from django.contrib.auth import authenticate, login as dlogin, logout as dlogout
from django.contrib.auth.models import User
from django.contrib import messages
from .models import *



def welcome_page(request):
    suites = Room.objects.all()
    context = {"suites":suites}
    return render(request, "home.html", context)


def about(request):
    context = {}
    return render(request, "about.html", context)


def faqq(request):
    faq = FAQ.objects.all()
    if request.method == "POST":
        question = request.POST.get("question")
        fullname = request.POST.get("fullname")
        faq_obj = FAQ(question = question, fullname = fullname)
        faq_obj.save()
        messages.success(request, "Success!")
        return redirect(request.META.get("HTTP_REFERER"))
    context = {"faq":faq}
    return render(request, "faq.html", context)


def contact(request):
    if request.method == "POST":
        message = request.POST.get("message")
        email = request.POST.get("email")
        fullname = request.POST.get("fullname")
        contact_save_obj = ContactSave(message = message, email = email, fullname = fulname)
        contact_save_obj.save()
       
    context = {}
    return render(request, "contact.html", context)


def login_page(request):
    context = {}
    return render(request, "login.html", context)


def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password = password)
        if user is not None:
            dlogin(request, user)
            if username == "admin" or username == "admin_user" or username == "admin2":
                return redirect("admin-welcome-page")
            else:
                return redirect("welcome-page")
        messages.error(request, "Invalid Login Details")
        return redirect("login-page")
    else:
        return redirect("login-page")


def register_page(request):
    if request.method == "POST":
        username = request.POST.get("username")
        fullname = request.POST.get("fullname")
        cellphone = request.POST.get("cellphone")
        password = request.POST.get("password")
        user = User.objects.create_user(username = username, password = password, first_name = fullname, last_name = cellphone)
        user.save()
        wallet = Wallet(user = user, account_bal=0)
        wallet.save()
        return redirect("login-page")
    context = {}
    return render(request, "signup.html", context)
    

def logout_page(request):
    dlogout(request)
    return redirect("/")

app_core/templates/admin_templates/admin_home.html
{% extends 'admin_templates/base.html' %}

{% block title %} Home {% endblock %}

{% block content %}

<br><br><br><br> 
<!--Main layout-->
<main>
    <div class="container">

    {% include 'admin_templates/admin_nav.html' %}

    <h2 class="my-5 h2 text-center">Suite Requests</h2>
        <div class="table">
            <table class="table-stripped table-hovered table-bordered">
                <thead>
                    <tr>
                        <td>Accomodation ID</td>
                        <td>User ID</td>
                        <td>User Name</td>
                        <td>User Username</td>
                        <td>Suite ID</td>
                        <td>Suite Number</td>
                        <td>Wing Name</td>
                        <td>Wing Manager</td>
                        <td>Date</td>
                        <td>Action</td>
                    </tr>
                </thead>
                <tbody>
                    {% for request in requestss %}
                    <tr>
                        <td>{{request.id}}</td>
                        <td>{{request.user.id}}</td>
                        <td>{{request.user.first_name}}</td>
                        <td>{{request.user.username}}</td>
                        <td>{{request.room.id}}</td>
                        <td>{{request.room.room_number}}</td>
                        <td>{{request.room.wing.wing_name}}</td>
                        <td>{{request.room.wing.wing_manager.first_name}}</td>
                        <td>{{request.created_at}}</td>
                        {% if request.approved %}
                        <td><a href="{% url 'app:approve_or_disapprove' request.id %}" type="button" class="btn btn-danger">Disapprove</a></td>
                        {% else %}
                        <td><a href="{% url 'app:approve_or_disapprove' request.id %}" type="button" class="btn btn-success">Approve</a></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</main>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}hh

app_core/templates/admin_templates/admin_nav.html
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Admin Management</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
            aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

            <!-- Links -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'admin-welcome-page' %}">ManageSuiteRequests</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:manage-suite-change' %}">ManageChanges</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:manage-help-request' %}">ManageHelpRequests</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:manage-rule' %}">ManageRules</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:manage-room-service' %}">ManageRoomService</a>
                </li>
            </ul>

        </div>
        <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

app_core/templates/admin_templates/create_package.html
{% extends 'admin_templates/base.html' %}

{% block title %} CreatePackage  {% endblock %}

{% block content %} 

{% if request.user.is_authenticated %}
<br>
<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container wow fadeIn">

        <!-- Heading -->
        <br><br>
        <h2 class="my-5 h2 text-center text-primary">Create Suite Package</h2>

        <!--Grid row-->
        <div class="row">

        <!--Grid column-->
        <div class="col-md-11 mb-4">

            <!--Card-->
            <div class="card">

            <!--Card content-->
            <form class="card-body" action="{% url 'app:create-package' %}" method="POST"> {% csrf_token %}
                <!--email-->
                <div class="md-form mb-5">
                    <input type="text" id="name" class="form-control" name="name" placeholder="Deluxe" required>
                    <label for="name" class="">Package Name</label>
                </div>

                <!--description-->
                <div class="md-form mb-5">
                    <input type="text" id="description" class="form-control" name="description" placeholder="ac, tv neat & conducive" required>
                    <label for="description" class="">Description</label>
                </div>

                <!--charge-->
                <div class="md-form mb-5">
                    <input type="number" id="charge" class="form-control" name="charge" placeholder="₦40" required>
                    <label for="charge" class="">Price Charge</label>
                </div>

                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Create Suite Package</button>
                {% if messages %}
                    <hr class="mb-1">
                    {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <span class="btn btn-success btn-lg btn-block" type="button">{{message}}</span>
                    {% else %}
                    <span class="btn btn-danger btn-lg btn-block" type="button">{{message}}</span>
                    {% endif %}
                    {% endfor %}
                {% endif %}
            </form>

            </div>
            <!--/.Card-->

        </div>
        <!--Grid column-->
        {% else %}
        <br><br>
        <div class="card mt-5">
            <div class="card-body">
                <h5 class="text-danger">You don't have access to this page 😹😹😹😹😹😹😹😹😹😹</h5>
            </div>
        </div>
        {% endif %}
        </div>
        <!--Grid row-->
    </div>
</main>
<!--Main layout-->
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

app_core/templates/admin_templates/create_room_service.html
{% extends 'admin_templates/base.html' %}

{% block title %} CreateRoomService  {% endblock %}

{% block content %} 

{% if request.user.is_authenticated %}
<br>
<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container wow fadeIn">

        <!-- Heading -->
        <br><br>
        <h2 class="my-5 h2 text-center text-primary">Create Room Service</h2>

        <!--Grid row-->
        <div class="row">

        <!--Grid column-->
        <div class="col-md-11 mb-4">

            <!--Card-->
            <div class="card">

            <!--Card content-->
            <form class="card-body" action="{% url 'app:create-room-service' %}" method="POST"> {% csrf_token %}

                <!--first name-->
                <div class="md-form mb-5">
                    <input type="text" id="firstname" class="form-control" name="firstname" placeholder="" required>
                    <label for="firstname" class="">First Name</label>
                </div>

                <!--lastname -->
                <div class="md-form mb-5">
                    <input type="text" id="lastname" class="form-control" name="lastname" placeholder="" required>
                    <label for="lastname" class="">Last Name</label>
                </div>

                <!--lastname -->
                <div class="md-form mb-5">
                    <input type="text" id="cellphone" class="form-control" name="cellphone" placeholder="" required>
                    <label for="cellphone" class="">Cell Phone</label>
                </div>
                
                <!--wing manager-->
                <div class="md-form mb-5">
                    <select id="wing_name" class="form-control" name="wing_name" required>
                        <option>Wing</option>
                        {% for wing in wings  %}
                            <option value="{{wing.id}}">Wing: {{wing.wing_name}} | Manager: {{wing.wing_manager.first_name}} - {{wing.wing_manager.last_name}}</option>
                        {% endfor %}
                    </select>
                </div>

                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Create Wing</button>
                {% if messages %}
                    <hr class="mb-1">
                    {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <span class="btn btn-success btn-lg btn-block" type="button">{{message}}</span>
                    {% else %}
                    <span class="btn btn-danger btn-lg btn-block" type="button">{{message}}</span>
                    {% endif %}
                    {% endfor %}
                {% endif %}
            </form>

            </div>
            <!--/.Card-->

        </div>
        <!--Grid column-->
        {% else %}
        <br><br>
        <div class="card mt-5">
            <div class="card-body">
                <h5 class="text-danger">You don't have access to this page 😹😹😹😹😹😹😹😹😹😹</h5>
            </div>
        </div>
        {% endif %}
        </div>
        <!--Grid row-->
    </div>
</main>
<!--Main layout-->
<br><br><br><br><br><br><br><br><br><br>
{% endblock %}

app_core/templates/admin_templates/create_suite.html
{% extends 'admin_templates/base.html' %}

{% block title %} CreateSuite  {% endblock %}

{% block content %} 

{% if request.user.is_authenticated %}
<!--Main layout-->
<main class="mt-4 pt-4">
    <div class="container wow fadeIn">

        <!-- Heading -->
        <br><br>
        <h2 class="my-5 h2 text-center text-primary">Create Suite</h2>

        <!--Grid row-->
        <div class="row">

        <!--Grid column-->
        <div class="col-md-11 mb-4">

            <!--Card-->
            <div class="card">

            <!--Card content-->
            <form class="card-body" action="{% url 'app:create-suite' %}" method="POST" enctype="multipart/form-data"> {% csrf_token %}
                
                <!--name-->
                <div class="md-form mb-5">
                    <input type="number" id="room_number" class="form-control" name="room_number" placeholder="1" required>
                    <label for="room_number" class="">Room Number</label>
                </div>

                <!--tag-->
                <div class="md-form mb-5">
                    <input type="text" id="room_tag" class="form-control" name="room_tag" placeholder="new" required>
                    <label for="room_tag" class="">Room Tag</label>
                </div>

                <div class="md-form mb-5">
                    <input type="text" id="room_condition" class="form-control" name="room_condition" placeholder="sharp" required>
                    <label for="room_condition" class="">Room Condition</label>
                </div>

                <!--wing-->
                <div class="md-form mb-5">
                    <select id="room_option" class="form-control" name="wing_name" placeholder="" required>
                        <option>Wing</option>
                        {% for wing in wings %}
                            <option value="{{wing.id}}">{{wing.wing_name}} Wing | Manager: {{wing.wing_manager.first_name}} {{wing.wing_manager.last_name}}</option>
                        {% endfor %}
                    </select>
                </div>

                <!--wing-->
                <div class="md-form mb-5">
                    <select id="package_name" class="form-control" name="package_name" placeholder="" required>
                        <option>Package</option>
                        {% for package in packages %}
                            <option value="{{package.id}}">{{package.name}} Package @ ₦{{package.charge}} per night!</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="md-form mb-5">
                    <input type="file" id="image1" class="form-control" name="image1" required>
                    <!-- <label for="image1" class="">Image One</label> -->
                </div>

                <div class="md-form mb-5">
                    <input type="file" id="image2" class="form-control" name="image2" required>
                    <!-- <label for="image2" class="">Image Two</label> -->
                </div>

                <div class="md-form mb-5">
                    <input type="file" id="image3" class="form-control" name="image3" required>
                    <!-- <label for="image3" class="">Image Three</label> -->
                </div>

                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Create New Suite</button>
                {% if messages %}
                    <hr class="mb-1">
                    {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <span class="btn btn-success btn-lg btn-block" type="button">{{message}}</span>
                    {% else %}
                    <span class="btn btn-danger btn-lg btn-block" type="button">{{message}}</span>
                    {% endif %}
                    {% endfor %}
                {% endif %}
            </form>

            </div>
            <!--/.Card-->

        </div>
        <!--Grid column-->
        {% else %}
        <br><br>
        <div class="card mt-5">
            <div class="card-body">
                <h5 class="text-danger">You don't have access to this page 😹😹😹😹😹😹😹😹😹😹</h5>
            </div>
        </div>
        {% endif %}
        </div>
        <!--Grid row-->
    </div>
</main>
<!--Main layout-->

{% endblock %}

app_core/templates/admin_templates/create_wing.html
{% extends 'admin_templates/base.html' %}

{% block title %} CreateWing  {% endblock %}

{% block content %} 

{% if request.user.is_authenticated %}
<br>
<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container wow fadeIn">

        <!-- Heading -->
        <br><br>
        <h2 class="my-5 h2 text-center text-primary">Create Suite Wing</h2>

        <!--Grid row-->
        <div class="row">

        <!--Grid column-->
        <div class="col-md-11 mb-4">

            <!--Card-->
            <div class="card">

            <!--Card content-->
            <form class="card-body" action="{% url 'app:create-wing' %}" method="POST"> {% csrf_token %}

                <!--wing name-->
                <div class="md-form mb-5">
                    <input type="text" id="wing_name" class="form-control" name="wing_name" placeholder="Kings" required>
                    <label for="wing_name" class="">Wing Name</label>
                </div>

                <!--wing number-->
                <div class="md-form mb-5">
                    <input type="number" id="wing_number" class="form-control" name="wing_number" placeholder="1" required>
                    <label for="wing_number" class="">Wing Number</label>
                </div>
                
                <!--wing manager-->
                <div class="md-form mb-5">
                    <select id="room_option" class="form-control" name="wing_manager" required>
                        <option>Choose Wing Manager</option>
                        {% for manager in wing_managers  %}
                            <option value="{{manager.id}}">Full Name: {{manager.first_name}} {{manager.last_name}} | Email: {{manager.email}}</option>
                        {% endfor %}
                    </select>
                </div>

                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Create Wing</button>
                {% if messages %}
                    <hr class="mb-1">
                    {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <span class="btn btn-success btn-lg btn-block" type="button">{{message}}</span>
                    {% else %}
                    <span class="btn btn-danger btn-lg btn-block" type="button">{{message}}</span>
                    {% endif %}
                    {% endfor %}
                {% endif %}
            </form>

            </div>
            <!--/.Card-->

        </div>
        <!--Grid column-->
        {% else %}
        <br><br>
        <div class="card mt-5">
            <div class="card-body">
                <h5 class="text-danger">You don't have access to this page 😹😹😹😹😹😹😹😹😹😹</h5>
            </div>
        </div>
        {% endif %}
        </div>
        <!--Grid row-->
    </div>
</main>
<!--Main layout-->
<br><br><br><br><br><br><br><br><br><br>
{% endblock %}

app_core/templates/admin_templates/navbar.html
  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light scrolling-navbar bg-custom">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'admin-welcome-page' %}">
        <strong class="text-primary">HMS</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'admin-welcome-page' %}"><b>Dashboard</b></a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'app:create-package' %}"><b>Create Package</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'app:create-wing-manager' %}"><b>Create Manager</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'app:create-wing' %}"><b>Create Wing</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'app:create-suite' %}"><b>Create Suite</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'app:create-room-service' %}"><b>Create RoomService</b></a>
          </li>
          {% endif %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'logout-user' %}" class="nav-link border border-light rounded waves-effect">
              <b class="text-danger mr-2">Logout</b>[<i class="fas fa-user mr-2"> {{ request.user.username}}] </i>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'login-page' %}"><b>Login</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'register-user' %}"><b>Register</b></a>
          </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->
  