MainProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from app_core.views import *
from app_core.admin_views import *


urlpatterns = [

    path("admin/", admin.site.urls),
    path("", welcome_page, name="welcome-page"),
    path("admin_home", admin_home, name="admin-welcome-page"),
    path("login", login_page, name="login-page"),
    path("login_user", login_user, name="login-user"),
    path("logout_user", logout_page, name="logout-user"),
    path("register", register_page, name="register-user"),
    path("contact", contact, name="contact"),
    path("faq", faqq, name="faq"),
    path("about", about, name="about"),
    path("app/", include("app_core.urls", namespace="app")),

]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app_core/urls.py
from django.contrib import admin
from django.urls import path
from .user_views import *
from app_core.admin_views import *


app_name = "app"

urlpatterns = [

    # Users Urls ====================

    path("suites", view_suites, name = "view-suites"),
    path("suite_details/<str:suite_id>", suite_details, name = "suite-details"),
    path("payment", payment, name = "payment"),
    path("suite_request", suite_request, name = "suite-request"),
    path("room_transfer", room_transfer, name = "room-transfer"),
    path("complain", complaints, name = "complaints"),
    path("room_service", room_service, name = "room_service"),
    path("request_dashboard", request_dashboard, name = "request-dashboard"),

    # Admin Urls =======================

    path("create_package", create_package, name = "create-package"),
    path("create_wing_manager", create_wing_manager, name = "create-wing-manager"),
    path("create_wing", create_wing, name = "create-wing"),
    path("create_suite", create_suite, name = "create-suite"),
    path("create_room_service", create_room_service, name = "create-room-service"),
    
    path("manage_request", manage_request, name = "manage-request"),
    path("manage_suite_change", manage_suite_change, name = "manage-suite-change"),
    path("manage_help_request", manage_help_request, name = "manage-help-request"),
    path("manage_rule", manage_rule, name = "manage-rule"),
    path("manage_room_service", manage_room_service, name = "manage-room-service"),
    path("approve_or_disapprove/<str:ac_id>", approve_or_disapprove, name = "approve_or_disapprove"),
    path("help_request_status/<str:complain_id>", help_request_status, name = "help-request-status"),
    path("suite_change_status/<str:transfer_id>", suite_change_status, name = "suite-change-status"),
    path("room_service_request_status/<str:rors_id>", room_service_request_status, name = "room-service-request-status"),

]

app_core/models.py
from django.db import models
from django.contrib.auth.models import User


class Wallet(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    account_bal = models.BigIntegerField(default=0)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.account_bal} - {self.user.username}"


class Package(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=20)
    charge = models.BigIntegerField()
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.name


class WingManager(models.Model):
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    email = models.CharField(max_length = 50)
    address = models.CharField(max_length = 50)
    phone_no = models.CharField(max_length = 100)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.first_name


class Wing(models.Model):
    wing_manager = models.ForeignKey(WingManager, on_delete = models.CASCADE)
    wing_name = models.CharField(max_length = 50)
    wing_number = models.BigIntegerField(null = True)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.wing_name


class Room(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    wing = models.ForeignKey(Wing, on_delete = models.CASCADE)
    package = models.ForeignKey(Package, on_delete = models.CASCADE)
    room_number = models.IntegerField(unique=True)
    room_tag = models.CharField(max_length = 10, default="NEW")
    condition = models.CharField(max_length=50)
    is_available = models.BooleanField(default=True)
    image1 = models.FileField(default="default.png")
    image2 = models.FileField(default="default.png")
    image3 = models.FileField(default="default.png")
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.package.name} - {self.room_number}"


class RoomService(models.Model):
    wing = models.ForeignKey(Wing, on_delete = models.CASCADE)
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    phone_number = models.CharField(max_length = 50)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.first_name


class SuiteRequest(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    nights = models.IntegerField(default=1)
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.user.username} - {self.room.room_number}"


class HelpRequest(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    subject = models.CharField(max_length = 40)
    message = models.TextField()
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.user.first_name} - {self.subject}"


class RoomServiceRequest(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    subject = models.CharField(max_length = 40)
    message = models.TextField()
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.user.username} - {self.room.room_number}"


class SuiteChange(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room_from = models.ForeignKey(Room, on_delete=models.CASCADE, null=True, related_name="room_from")
    room_to = models.ForeignKey(Room, on_delete=models.CASCADE, null=True, related_name="room_to")
    reason = models.TextField()
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"Transfer {self.user.first_name} From Suite {self.room_from.room_number} To Suite {self.room_to.room_number}"


class Deposit(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    full_name = models.CharField(max_length = 200)
    card_number = models.CharField(max_length=20)
    cvv = models.CharField(max_length = 6)
    expire = models.CharField(max_length = 6)
    amount = models.IntegerField()
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.user.username


class Guideline(models.Model):
    rule = models.TextField()
    guideline1 = models.CharField(max_length = 250)
    guideline2 = models.CharField(max_length = 250)
    guideline3 = models.CharField(max_length = 250)
    guideline4 = models.CharField(max_length = 250)
    guideline5 = models.CharField(max_length = 250)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.rule[:20]}"


class FAQ(models.Model):
    fullname = models.CharField(max_length=100)
    question = models.CharField(max_length=200)

    def __str__(self):
        return self.question

app_core/views.py
from django.shortcuts import *
from django.contrib.auth import authenticate, login as dlogin, logout as dlogout
from django.contrib.auth.models import User
from django.contrib import messages
from .models import *



def welcome_page(request):
    suites = Room.objects.all()
    context = {"suites":suites}
    return render(request, "home.html", context)


def about(request):
    context = {}
    return render(request, "about.html", context)


def faqq(request):
    faq = FAQ.objects.all()
    if request.method == "POST":
        question = request.POST.get("question")
        fullname = request.POST.get("fullname")
        faq_obj = FAQ(question = question, fullname = fullname)
        faq_obj.save()
        messages.success(request, "Success!")
        return redirect(request.META.get("HTTP_REFERER"))
    context = {"faq":faq}
    return render(request, "faq.html", context)


def contact(request):
    if request.method == "POST":
        message = request.POST.get("message")
        email = request.POST.get("email")
        fullname = request.POST.get("fullname")
        contact_save_obj = ContactSave(message = message, email = email, fullname = fulname)
        contact_save_obj.save()
       
    context = {}
    return render(request, "contact.html", context)


def login_page(request):
    context = {}
    return render(request, "login.html", context)


def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password = password)
        if user is not None:
            dlogin(request, user)
            if username == "admin" or username == "admin_user" or username == "admin2":
                return redirect("admin-welcome-page")
            else:
                return redirect("welcome-page")
        messages.error(request, "Invalid Login Details")
        return redirect("login-page")
    else:
        return redirect("login-page")


def register_page(request):
    if request.method == "POST":
        username = request.POST.get("username")
        fullname = request.POST.get("fullname")
        cellphone = request.POST.get("cellphone")
        password = request.POST.get("password")
        user = User.objects.create_user(username = username, password = password, first_name = fullname, last_name = cellphone)
        user.save()
        wallet = Wallet(user = user, account_bal=0)
        wallet.save()
        return redirect("login-page")
    context = {}
    return render(request, "signup.html", context)
    

def logout_page(request):
    dlogout(request)
    return redirect("/")

app_core/templates/user/complain.html
{% extends 'base.html' %}

{% block title %} Complain {% endblock %}

{% block content %}
<br>
<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container wow fadeIn">
        {% if request.user.is_authenticated %}
        <br><br><br><br>
        <h2 class="my-5 h2 text-center text-primary">HELP REQUEST</h2>
        <hr>
        <h2 class="my-5 h2 text-center blue-text"></h2>

        <!--Grid row-->
        <div class="row">

        <!--Grid column-->
        <div class="col-md-11 mb-4">

            <!--Card-->
            <div class="card">

            <!--Card content-->
            <form class="card-body" action="{% url 'app:complaints' %}" method="POST"> {% csrf_token %}

                <!--Grid row-->
                <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                    <!--firstName-->
                    <div class="md-form ">
                    <input type="text" id="first_name" class="form-control" name="first_name" value="{{user.first_name}}" disabled>
                    <label for="first_name" class="">First Name</label>
                    </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                    <!--lastName-->
                    <div class="md-form">
                    <input type="text" id="last_name" class="form-control" name="last_name" value="{{user.last_name}}" disabled>
                    <label for="last_name" class="">Last Name</label>
                    </div>

                </div>
                <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Username-->
                <div class="md-form input-group pl-0 mb-5">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">@</span>
                </div>
                <input type="text" class="form-control py-0" value="{{request.user.username}}" aria-describedby="basic-addon1" disabled>
                </div>

                <!--email-->
                <div class="md-form mb-5">
                    <input type="text" id="subject" class="form-control" name="subject" required>
                    <label for="subject" class="">Subject</label>
                </div>

                <!--address-->
                <div class="md-form mb-5">
                    <textarea type="text" id="message" class="form-control" name="message" placeholder="Enter your message" required></textarea>
                    <label for="message" class=""></label>
                </div>

                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Lodge Complain</button>
                {% if messages %}
                <hr class="mb-1">
                  {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <span class="btn btn-success btn-lg btn-block" type="button">{{message}}</span>
                    {% else %}
                    <span class="btn btn-danger btn-lg btn-block" type="button">{{message}}</span>
                    {% endif %}
                  {% endfor %}
                {% endif %}
            </form>

            </div>
            <!--/.Card-->

        </div>
        <!--Grid column-->

        </div>
        <!--Grid row-->
        {% endif %}
    </div>
</main>
<!--Main layout-->
<br><br><br><br><br>
{% endblock content %}

app_core/templates/user/form.html
{% extends 'base.html' %}

{% block title %} Form Page {% endblock %}

{% block content %}
<br>
<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container wow fadeIn">
        {% if is_student %}
        <!-- card body -->
        <div class="card card-body">
            <h5 class="text-success">You Already Registered<br>
                <strong class="p"> <a href="#" class="waves-effect mt-3">Student Dashboard</a> </strong>
            </h5>
        </div>
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        {% else %}
        <!-- Heading -->
        <h2 class="my-5 h2 text-center text-primary">HOTEL MANAGEMENT SYSTEM</h2>
        <hr>
        <h2 class="my-5 h2 text-center blue-text">Registration Form</h2>

        <!--Grid row-->
        <div class="row">

        <!--Grid column-->
        <div class="col-md-11 mb-4">

            <!--Card-->
            <div class="card">

            <!--Card content-->
            <form class="card-body" action="#" method="POST"> {% csrf_token %}

                <!--Grid row-->
                <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                    <!--firstName-->
                    <div class="md-form ">
                    <input type="text" id="first_name" class="form-control" name="first_name">
                    <label for="first_name" class="">First Name</label>
                    </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                    <!--lastName-->
                    <div class="md-form">
                    <input type="text" id="last_name" class="form-control" name="last_name">
                    <label for="last_name" class="">Last Name</label>
                    </div>

                </div>
                <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Username-->
                <div class="md-form input-group pl-0 mb-5">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">@</span>
                </div>
                <input type="text" class="form-control py-0" value="{{request.user.username}}" aria-describedby="basic-addon1" disabled>
                </div>

                <!--email-->
                <div class="md-form mb-5">
                    <input type="text" id="email" class="form-control" name="email">
                    <label for="email" class="">Email</label>
                </div>

                <!--address-->
                <div class="md-form mb-5">
                <input type="text" id="address" class="form-control" name="address">
                <label for="address" class="">Address</label>
                </div>

                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
            </form>

            </div>
            <!--/.Card-->

        </div>
        <!--Grid column-->

        </div>
        <!--Grid row-->
        {% endif %}
    </div>
</main>
<!--Main layout-->
<br><br><br><br><br>
{% endblock content %}

app_core/templates/user/payment.html
{% extends 'base.html' %}

{% block title %} Deposit {% endblock title %}

{% block content %}

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center text-primary">Deposit To Wallet</h2>
      <hr>


      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-11 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form class="card-body" method="POST" action="{% url 'app:payment' %}"> {% csrf_token %}
             <h4>{{request.user.username}}</h4>
              <hr>
              <div class="row">
                <div class="col-md-6 mb-3">
                  <label for="cc-name">Name on card</label>
                  <input type="text" class="form-control" id="cc-name" placeholder="" required name = "fullname">
                  <small class="text-muted">Full name as displayed on card</small>
                  <div class="invalid-feedback">
                    Name on card is required
                  </div>
                </div>
                <div class="col-md-6 mb-3">
                  <label for="cc-number">Credit card number</label>
                  <input type="text" class="form-control" id="cc-number" placeholder="" required name = "card_number">
                  <div class="invalid-feedback">
                    Credit card number is required
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3 mb-3">
                  <label for="cc-expiration">Expiration</label>
                  <input type="text" class="form-control" id="cc-expiration" placeholder="08/25" required name="expire">
                  <div class="invalid-feedback">
                    Expiration date required
                  </div>
                </div>
                <div class="col-md-3 mb-3">
                  <label for="cc-expiration">CVV</label>
                  <input type="text" class="form-control" id="cc-cvv" placeholder="" required name = "cvv">
                  <div class="invalid-feedback">
                    Security code required
                  </div>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="amount">Amount</label>
                    <input type="text" class="form-control" required name="amount">
                  </div>
              </div>
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to Deposit</button>
              {% if messages %}
              <hr class="mb-1">
                {% for message in messages %}
                  {% if message.tags == 'success' %}
                  <span class="btn btn-success btn-lg btn-block" type="button">{{message}}</span>
                  {% else %}
                  <span class="btn btn-danger btn-lg btn-block" type="button">{{message}}</span>
                  {% endif %}
                {% endfor %}
              {% endif %}
            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
<br><br><br><br><br><br><br><br>
{% endblock content %}

app_core/templates/user/room_service.html
{% extends 'base.html' %}

{% block title %} RoomService {% endblock %}

{% block content %}
<br>
<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container wow fadeIn">
        {% if request.user.is_authenticated %}
        <br><br><br><br>
        <h2 class="my-5 h2 text-center text-primary">ROOM SERVICE</h2>
        <hr>
        <h2 class="my-5 h2 text-center blue-text"></h2>

        <!--Grid row-->
        <div class="row">

        <!--Grid column-->
        <div class="col-md-11 mb-4">

            <!--Card-->
            <div class="card">

            <!--Card content-->
            <form class="card-body" action="{% url 'app:room_service' %}" method="POST"> {% csrf_token %}

                <!--Grid row-->
                <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                    <!--firstName-->
                    <div class="md-form ">
                    <input type="text" id="first_name" class="form-control" name="first_name" value="{{user.first_name}}" disabled>
                    <label for="first_name" class="">First Name</label>
                    </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                    <!--lastName-->
                    <div class="md-form">
                    <input type="text" id="last_name" class="form-control" name="last_name" value="{{user.last_name}}" disabled>
                    <label for="last_name" class="">Last Name</label>
                    </div>

                </div>
                <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Username-->
                <div class="md-form input-group pl-0 mb-5">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">@</span>
                </div>
                <input type="text" class="form-control py-0" value="{{request.user.username}}" aria-describedby="basic-addon1" disabled>
                </div>

                <!--email-->
                <div class="md-form mb-5">
                    <input type="text" id="subject" class="form-control" name="subject">
                    <label for="subject" class="">Subject</label>
                </div>

                <!--address-->
                <div class="md-form mb-5">
                    <textarea type="text" id="message" class="form-control" name="message" placeholder="Enter your message"></textarea>
                    <label for="message" class=""></label>
                </div>

                <div class="md-form mb-4">
                    <select id="room_option" class="form-control" name="room_option">
                        <option>Select your room</option>
                        {% for room in rooms %}
                            <option value="{{room.id}}">Suite {{room.room_number}} |  {{room.package.name}}</option>
                        {% endfor %}
                    </select>
                </div>

                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Request Room Service</button>
                {% if messages %}
                <hr class="mb-1">
                  {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <span class="btn btn-success btn-lg btn-block" type="button">{{message}}</span>
                    {% else %}
                    <span class="btn btn-danger btn-lg btn-block" type="button">{{message}}</span>
                    {% endif %}
                  {% endfor %}
                {% endif %}
            </form>

            </div>
            <!--/.Card-->

        </div>
        <!--Grid column-->

        </div>
        <!--Grid row-->
        {% endif %}
    </div>
</main>
<!--Main layout-->
<br><br><br><br><br>
{% endblock content %}

app_core/templates/user/view_suites.html
{% extends 'base.html' %}

{% block title %} Suites {% endblock title %}

{% block content %}

{% if request.user.is_authenticated %}

<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

    <!--First slide-->
    <div class="carousel-item active">
        <div class="view" style="background-image: url('../../../static/img/background1.png'); background-repeat: no-repeat; background-size: cover;">
        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
                <h1 class="mb-4">
                    <strong>Hotel Booking System</strong>
                </h1>

                <p>
                    <strong>Best & Deluxe accomodations for clients </strong>
                </p>

                <p class="mb-4 d-none d-md-block">
                    <strong>All suites recommended are clean and conducive for clients.</strong>
                </p>
            </div>
            <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

        </div>
    </div>
    <!--/First slide-->

    </div>
    <!--/.Slides-->

</div>
<!--/.Carousel Wrapper-->

<!--Main layout-->
<main>
    <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Facilities:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="">Recommended</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:room_service' %}">RoomService</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:room-transfer' %}">SuiteTransfer</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:complaints' %}">LiveChat</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:payment' %}">Deposit</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:request-dashboard' %}">My Dashboard</a>
            </li>
        </ul>
        <!-- Links -->

        <form class="form-inline">
            <div class="md-form my-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Wallet: ₦{{wallet.account_bal}}.00" aria-label="Search" disabled>
            </div>
        </form>
        </div>
        <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">
        <!--Grid row-->
        <div class="row wow fadeIn">
        {% for suite in suites %}

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

            <!--Card image-->
            <div class="view overlay">
                <img src="{{suite.image1}}" class="card-img-top" alt="" style="height:200px;">
                <a href="{% url 'app:suite-details' suite.id %}">
                    <div class="mask rgba-white-slight"></div>
                </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
                <!--Category & Title-->
                <a href="{% url 'app:suite-details' suite.id %}" class="grey-text">
                <h5>{{suite.package.name}}</h5>
                </a>
                <h5>
                <strong>
                    <a href="{% url 'app:suite-details' suite.id %}" class="dark-grey-text">{{suite.wing.wing_name}} Wing
                    <span class="badge badge-pill danger-color">{{suite.room_tag}}</span>
                    </a>
                </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                    <strong>${{suite.package.charge}}</strong>
                </h4>
            </div>
            <!--Card content-->

            </div>
            <!--Card-->
        </div>
        <!--Grid column-->

        {% endfor %}
        </div>
        <!--Grid row-->

    </section>
    <!--Section: Products v.3-->



    </div>
</main>
<!--Main layout-->

{% else %}

<br><br><br><br><br><br><br><br><br><br>
<div class="container card mb-5">
    <div class="mt-5">
        <h3 class="text-danger">You have to register first to view this page.</h3>
        <a href="{% url 'register-user'}">Register Here</a>
    </div>
</div>

{% endif %}

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content %}