MainProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from app_core.views import *
from app_core.admin_views import *


urlpatterns = [

    path("admin/", admin.site.urls),
    path("", welcome_page, name="welcome-page"),
    path("admin_home", admin_home, name="admin-welcome-page"),
    path("login", login_page, name="login-page"),
    path("login_user", login_user, name="login-user"),
    path("logout_user", logout_page, name="logout-user"),
    path("register", register_page, name="register-user"),
    path("contact", contact, name="contact"),
    path("faq", faqq, name="faq"),
    path("about", about, name="about"),
    path("app/", include("app_core.urls", namespace="app")),

]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app_core/urls.py
from django.contrib import admin
from django.urls import path
from .user_views import *
from app_core.admin_views import *


app_name = "app"

urlpatterns = [

    # Users Urls ====================

    path("suites", view_suites, name = "view-suites"),
    path("suite_details/<str:suite_id>", suite_details, name = "suite-details"),
    path("payment", payment, name = "payment"),
    path("suite_request", suite_request, name = "suite-request"),
    path("room_transfer", room_transfer, name = "room-transfer"),
    path("complain", complaints, name = "complaints"),
    path("room_service", room_service, name = "room_service"),
    path("request_dashboard", request_dashboard, name = "request-dashboard"),

    # Admin Urls =======================

    path("create_package", create_package, name = "create-package"),
    path("create_wing_manager", create_wing_manager, name = "create-wing-manager"),
    path("create_wing", create_wing, name = "create-wing"),
    path("create_suite", create_suite, name = "create-suite"),
    path("create_room_service", create_room_service, name = "create-room-service"),
    
    path("manage_request", manage_request, name = "manage-request"),
    path("manage_suite_change", manage_suite_change, name = "manage-suite-change"),
    path("manage_help_request", manage_help_request, name = "manage-help-request"),
    path("manage_rule", manage_rule, name = "manage-rule"),
    path("manage_room_service", manage_room_service, name = "manage-room-service"),
    path("approve_or_disapprove/<str:ac_id>", approve_or_disapprove, name = "approve_or_disapprove"),
    path("help_request_status/<str:complain_id>", help_request_status, name = "help-request-status"),
    path("suite_change_status/<str:transfer_id>", suite_change_status, name = "suite-change-status"),
    path("room_service_request_status/<str:rors_id>", room_service_request_status, name = "room-service-request-status"),

]

templates/about.html
{% extends 'base.html' %}

{% block title %} About {% endblock title %}

{% block content %}

<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

    <!--First slide-->
    <div class="carousel-item active">
        <div class="view" style="background-image: url('../static/img/background4.png'); background-repeat: no-repeat; background-size: cover;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
                <h1 class="mb-4">
                    <strong>About Our Hotel Management System</strong>
                </h1>
            </div>
            <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

        </div>
    </div>
    <!--/First slide-->

    </div>
    <!--/.Slides-->

</div>
<!--/.Carousel Wrapper-->

<!--Main layout-->
<main>
    <div class="container"><br>

    <!--Section: Products v.3-->
    <section class="mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
            <div class="card">
                <div class="card-header">
                    <h1>About Us</h1>
                </div>
                <div class="card-body">
                    <p>Welcome to the future of hotel management with our cutting-edge Hotel Management System. 
                        We are dedicated to revolutionizing the way hotels operate, streamlining processes, 
                        enhancing guest experiences, and empowering hoteliers with innovative technology. 
                        Our commitment to excellence drives us to provide you with a comprehensive solution that caters to all your hotel management needs.</p>
                    <hr>
                    <h2>Our Vision</h2>
                    <p>At the core of our mission is the vision of a hospitality industry that seamlessly 
                        blends modern technology with traditional hospitality values. We envision a world 
                        where hoteliers can focus on creating memorable guest experiences, while our Hotel Management 
                        System handles the complexities of day-to-day operations effortlessly.</p>
                    <hr>
                    <h2>Who We Are</h2>
                    <p>We are a team of passionate and experienced professionals in the fields of technology and 
                        hospitality. With years of expertise, we have developed a Hotel Management System that is 
                        designed to cater to hotels of all sizes and types, from boutique bed-and-breakfasts to luxury resorts.</p>
                    <hr>
                    <h2>Our Core Values</h2>
                    <ul>
                        <li><strong>Innovation:</strong> We are committed to staying at the forefront of technological advancements, ensuring that our system is always equipped with the latest features and capabilities.</li>
                        <li><strong>Simplicity:</strong> We believe that technology should be easy to use. Our user-friendly interface and intuitive design make hotel management a breeze.</li>
                        <li><strong>Reliability:</strong> Trust is paramount in the hospitality industry. Our system is robust, secure, and reliable, ensuring uninterrupted service for your guests.</li>
                        <li><strong>Customer-Centric:</strong> We put our customers first. Your success is our success, and we are dedicated to providing exceptional support and guidance whenever you need it.</li>
                    </ul>
                </div>
            </div>
        </div>
        <!--Grid row-->

    </section>
    <!--Section: Products v.3-->

    </div>
</main>
<!--Main layout-->

<br><br><br><br><br><br>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>HMS | {% block title %} {% endblock title %} </title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/main.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 80vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 120vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 120vh;
      }
    }

  </style>

</head>

<body style="background-image: url(); background-size: cover;">

    {% include 'navbar.html' %}

    {% block content %}

    {% endblock content %}

    {% include 'footer.html' %}

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

</html>

templates/contact.html
{% extends 'base.html' %}

{% block title %} Contact {% endblock title %}

{% block content %}

<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

    <!--First slide-->
    <div class="carousel-item active">
        <div class="view" style="background-image: url('../static/img/background4.png'); background-repeat: no-repeat; background-size: cover;">
        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
                <h1 class="mb-4">
                    <strong>Contact Our Hotel Management System</strong>
                </h1>
            </div>
            <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
        </div>
    </div>
    <!--/First slide-->
    </div>
    <!--/.Slides-->
</div>
<!--/.Carousel Wrapper-->

<!--Main layout-->
<main>
    <div class="container"><br>

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
            <div class="card card-body">
            <h3> Phone Number: 728-29871-21 </h3>
                Email: info@hotel.com
                Please be sure that all your enquiries and complaints will be attended to within 48hours.
            </div>
        </div>
        <!--Grid row-->
    </section>
    <!--Section: Products v.3-->
    </div>
</main>
<!--Main layout-->
<br>
{% endblock content %}

templates/faq.html
{% extends 'base.html' %}

{% block title %} FAQ {% endblock title %}

{% block content %}

<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

    <!--First slide-->
    <div class="carousel-item active">
        <div class="view" style="background-image: url('../static/img/background4.png'); background-repeat: no-repeat; background-size: cover;">
        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
                <h1 class="mb-4">
                    <strong>ASK US ?</strong>
                </h1>
            </div>
            <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
        </div>
    </div>
    <!--/First slide-->
    </div>
    <!--/.Slides-->
</div>
<!--/.Carousel Wrapper-->

<!--Main layout-->
<main>
    <div class="container"><br>

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
            <!--Card content-->
            <form class="card-body" action="{% url 'faq' %}" method="POST"> {% csrf_token %}

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12 mb-2">
                        <!--firstName-->
                        <div class="md-form">
                            <input type="text" id="fullname" class="form-control" name="fullname" required>
                            <label for="fullname" class="">Full Name</label>
                        </div>
                    </div>
                    <!--Grid column-->

                
                    <!--message-->
                    <div class="col-md-12 mb-2">
                        <div class="md-form mb-5">
                            <textarea class="form-control" type="text" id="question" placeholder="Ask Us ?" name="question" required></textarea>
                        </div>
                    </div>

                </div>
                <!--Grid row-->
                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
                {% if messages %}
                <hr class="mb-1">
                {% for message in messages %}
                  {% if message.tags == 'success' %}
                  <span class="btn btn-success btn-lg btn-block" type="button">{{message}}</span>
                  {% else %}
                  <span class="btn btn-danger btn-lg btn-block" type="button">{{message}}</span>
                  {% endif %}
                {% endfor %}
              {% endif %}
            </form>
        </div>
        <!--Grid row-->
        <div class="container">
            <div class="card">
                <div class="card-header">
                    <h1>General FAQ</h1>
                </div>
                <div class="card-body">
                  {% for f in faq %}
                    <h4>By {{f.fullname}}</h4>
                    <p> {{f.question}} </p>
                    <hr>
                  {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <!--Section: Products v.3-->
    </div>
</main>
<!--Main layout-->
<br>
{% endblock content %}

templates/footer.html
  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn bg-custom">

    <!--Call to action-->
    <div class="pt-4">
      <!-- <a class="btn btn-outline-white" href="" role="button"> 
        Start -->
        <!-- <i class="fas fa-graduation-cap ml-2"></i> -->
      <!-- </a> -->
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    
    <div class="pb-4">
      <a href="https://www.facebook.com" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://github.com" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2023 Copyright @HotelManagement.com
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

templates/home.html
{% extends 'base.html' %}

{% block title %} Welcome {% endblock title %}

{% block content %}

<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

    <!--First slide-->
    <div class="carousel-item active">
        <div class="view" style="background-image: url('../static/img/background3.png'); background-repeat: no-repeat; background-size: cover;">
        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
                <h1 class="mb-4">
                    <strong>Hotel Management System</strong>
                </h1>

                <p>
                    <strong>VIEW OUR SUITES</strong>
                </p>
                {% if request.user.is_authenticated %}
                <a href="{% url 'app:view-suites' %}" class="btn btn-outline-white btn-lg">Book Now!
                    <!-- <i class="fas fa-graduation-cap ml-2"></i> -->
                </a>
                {% else %}
                <a href="{% url 'register-user' %}" class="btn btn-outline-white btn-lg">Sign Up Here Now
                    <!-- <i class="fas fa-graduation-cap ml-2"></i> -->
                </a>
                {% endif %}
            </div>
            <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

        </div>
    </div>
    <!--/First slide-->

    <!--Second slide-->
    <div class="carousel-item">
        <div class="view" style="background-image: url('../static/img/background7.png'); background-repeat: no-repeat; background-size: cover;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
                <strong>Our Booking System</strong>
            </h1>

            <p>
                <strong>BOOK WITH US TODAY</strong>
            </p>
            {% if request.user.is_authenticated%}
            <a href="{% url 'app:view-suites' %}" class="btn btn-outline-white btn-lg">Click Me
                <!-- <i class="fas fa-graduation-cap ml-2"></i> -->
            </a>
            {% else %}
            <a href="{% url 'register-user' %}" class="btn btn-outline-white btn-lg">Sign Up Here Now
                <!-- <i class="fas fa-graduation-cap ml-2"></i> -->
            </a>
            {% endif %}
            </div>
            <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

        </div>
    </div>
    <!--/Second slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
    </a>

    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

</div>
<!--/.Carousel Wrapper-->

<!--Main layout-->
<main>
    <div class="container"><br>

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
        {% for suite in suites %}

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

            <!--Card image-->
            <div class="view overlay">
                <img src="{{suite.image1}}" class="card-img-top" alt="" style="height:200px;">
                <a>
                    <div class="mask rgba-white-slight"></div>
                </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                <h5>{{suite.package.name}}</h5>
                </a>
                <h5>
                <strong>
                    <a href="" class="dark-grey-text"> {{suite.wing.wing_name}} Wing
                    <span class="badge badge-pill danger-color">{{suite.room_tag}}</span>
                    </a>
                </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                    <strong>${{suite.package.charge}}</strong>
                </h4>
            </div>
            <!--Card content-->

            </div>
            <!--Card-->

        </div>
        <!--Grid column-->

        {% endfor %}
        </div>
        <!--Grid row-->

    </section>
    <!--Section: Products v.3-->

    </div>
</main>
<!--Main layout-->

<br><br><br><br><br><br>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
<br><br><br><br>
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h1 class="text-primary text-center h1">Sign In</h1>
      <hr>
      <!-- <h2 class="my-5 h2 text-center blue-text">Sign In</h2> -->

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-10 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form class="card-body" action="{% url 'login-user' %}" method="POST"> {% csrf_token %}

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--firstName-->
                  <div class="md-form ">
                    <input type="text" id="username" class="form-control" name="username" placeholder="My Username" required>
                    <label for="username" class="">Username</label>
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--lastName-->
                  <div class="md-form">
                    <input type="password" id="password" class="form-control" name="password" placeholder="********" required>
                    <label for="password" class="">Password</label>
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Proceed to Login</button>
              <div class="text-muted mt-3">
                <h6>Don't have an account? <a href="{% url 'register-user' %}">Create Account</a></h6>
              </div>
              {% if messages %}
              <hr class="mb-1">
                {% for message in messages %}
                  {% if message.tags == 'success' %}
                  <span class="btn btn-success btn-lg btn-block" type="button">{{message}}</span>
                  {% else %}
                  <span class="btn btn-danger btn-lg btn-block" type="button">{{message}}</span>
                  {% endif %}
                {% endfor %}
              {% endif %}
            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
<br><br><br><br><br><br><br><br><br><br>
{% endblock content %}

templates/navbar.html
  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light scrolling-navbar bg-custom">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'welcome-page' %}">
        <h1 class="text-custom"><strong class="text-custom h1">HMS</strong></h1>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'welcome-page' %}"><b>Home</b></a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'app:view-suites' %}"><b>Suites Dashboard</b></a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'about' %}"><b>About</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'contact' %}"><b>Contact</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'faq' %}"><b>FAQ</b></a>
          </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'logout-user' %}" class="nav-link border border-light rounded waves-effect">
              <b class="text-danger mr-2">Logout</b><strong>[<i class="fas fa-user mr-2">{{ request.user.username}}] </i></strong>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'login-page' %}"><b>Login</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'register-user' %}"><b>Register</b></a>
          </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->
  

templates/signup.html
{% extends 'base.html' %}

{% block title %} Register {% endblock %}

{% block content %}
<br><br><br><br>
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h1 class="text-primary text-center h1">Create New Account</h1>
      <hr>
      <!-- <h2 class="my-5 h2 text-center blue-text">Create My Account</h2> -->

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-10 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form class="card-body" action="{% url 'register-user' %}" method="POST"> {% csrf_token %}

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--userName-->
                  <div class="md-form ">
                    <input type="text" id="fullname" class="form-control" name="fullname" placeholder="Jack Bauer" >
                    <label for="fullname" class="">Full Name</label>
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--lastName-->
                  <div class="md-form">
                    <input type="text" id="cellphone" class="form-control" name="cellphone" placeholder="55-372-371">
                    <label for="cellphone" class="">Cell Phone</label>
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--userName-->
                  <div class="md-form ">
                    <input type="text" id="username" class="form-control" name="username" placeholder="Bauer78">
                    <label for="username" class="">Username</label>
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--lastName-->
                  <div class="md-form">
                    <input type="password" id="password" class="form-control" name="password" placeholder="*******">
                    <label for="password" class="">Password</label>
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Sign Me Up</button>
              <div class="text-muted mt-3">
                <h6>Already have an account? <a href="{% url 'login-page' %}">Login</a></h6>
              </div>
            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
<br><br><br><br><br><br><br><br><br><br>
{% endblock content %}